default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
        exclude: test/data/schema/wrong_syntax.py
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: mkdocs.yml
  - repo: https://github.com/tcort/markdown-link-check
    rev: "v3.13.7"
    hooks:
      - id: markdown-link-check
        args: [-q]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ["--wrap", "120"]
        additional_dependencies:
          - mdformat-mkdocs
          - mdformat-tables
