site_name: Data as Code

repo_url: https://github.com/data-as-code/dac
edit_uri: tree/main/doc

nav:
  - Home: index.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - toc.follow

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # noqa


      emoji_generator: !!python/name:material.extensions.emoji.to_svg # noqa


  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # noqa


  - tables
  - toc:
      permalink: true
      toc_depth: 5
