site_name: Data as Code

repo_url: https://github.com/data-as-code/docs
edit_uri: edit/main/docs/

nav:
  - Home: index.md

theme:
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - toc.follow
  icon:
    edit: material/pencil
    view: material/eye

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji

      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - tables
  - toc:
      permalink: true
      toc_depth: 5
